name: dictionarylib
description: "Library for the sign language dictionary apps"
version: 0.0.7

publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider:
  collection:
  cupertino_icons:
  device_info_plus:
  dolphinsr_dart:
    git:
      url: https://github.com/banool/dolphhinsr_dart.git
      ref: master
  dots_indicator:
  edit_distance: ^0.5.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_cache_manager:
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_native_splash:
  go_router: 6.5.9
  http:
  intl:
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  launch_review:
  mailto:
  multi_select_flutter:
  package_info_plus:
  path_provider:
  settings_ui:
  shared_preferences:
  system_proxy:
  url_launcher:
  video_player:

dev_dependencies:
  build_runner: ^2.3.3
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
